# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin

import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun

x=np.array([10,40,20,30])
print(x)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.

x2=np.sort(x)
print(x2)


[10 40 20 30]
[10 20 30 40]


# Problem 2

In [32]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.

sayilar=np.array([10,15,30,45,60])
print(f"sayılar arrayi: {sayilar}")

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.

sayilar2=np.arange(5,15)
print("sayilar2 arrayi:",sayilar2)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.

numpy=np.arange(50,100,5)
print("numpy arrayi:",numpy)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.

numpy0=np.zeros(10)
print("numpy0 arrayi:",numpy0)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.

numpy1=np.ones(10)
print("numpy1 arrayi:",numpy1)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.

numpy2=np.linspace(0,100,5)
print("numpy2 arrayi:",numpy2)


# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.

random=np.random.randint(10,31, size=5)  #range ile aynı
print("random arrayi:",random)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.

random2=np.random.uniform(-1,1,10)   #.normal fonksiyonu da kullanılabilir
print("random arrayi:",random2)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

random_matris=np.random.randint(10,50, size=(3,5))
print("random_matris :",random_matris)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?

# axis=0 dikey # axis=1 yatay
print(random_matris.sum(axis=0))
print(random_matris.sum(axis=1))

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?

print(random_matris.max())
print(random_matris.min())
print(random_matris.mean())

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?

print(random_matris.argmax())

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

dizi=np.random.randint(10,20, size=9)              # :dan önce sayı konmazsa ilk rakamı alır :dan sonra sayı koymazsak son elemanı alır.
print(dizi[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.

print(dizi[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.

print(random_matris[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?

print(random_matris[1,2]) #[1][2] diye de yazılabilir.

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.

print(random_matris[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.

print(random_matris**2) # power fonksiyonu kullnanbilirsin

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.

random_matris2=np.random.randint(-50,50, size=(4,5))
print(random_matris2)
print(random_matris2[ (random_matris2%2==0) & (random_matris2>0)])

sayılar arrayi: [10 15 30 45 60]
sayilar2 arrayi: [ 5  6  7  8  9 10 11 12 13 14]
numpy arrayi: [50 55 60 65 70 75 80 85 90 95]
numpy0 arrayi: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
numpy1 arrayi: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
numpy2 arrayi: [  0.  25.  50.  75. 100.]
random arrayi: [22 26 24 19 18]
random arrayi: [-9.36042252e-04  6.39884254e-01  1.91971830e-01  4.60487227e-03
 -7.95308126e-01  5.06391697e-01  9.89312942e-01 -6.77754355e-01
  3.75825987e-01 -4.78818758e-01]
random_matris : [[32 42 31 31 35]
 [38 46 30 46 33]
 [36 12 10 40 37]]
[106 100  71 117 105]
[171 193 135]
46
10
33.266666666666666
6
[10 12 17]
[18 13 12 14 17 11 17 12 10]
[32 42 31 31 35]
30
[32 38 36]
[[1024 1764  961  961 1225]
 [1444 2116  900 2116 1089]
 [1296  144  100 1600 1369]]
[[ 13  38  46  14 -44]
 [-40  28  31  24  26]
 [ 39 -43  10 -30  28]
 [-28 -31  22 -14   6]]
[38 46 14 28 24 26 10 28 22  6]
