# Problem 1

In [3]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [25]:
# 1 - numpy kütüphanesini import edin

import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

matris=np.random.randint(2,10, size=5)
print(matris)

# 3 - matris'in boyutunu öğrenin

print(matris.ndim)

# 4 - matris'i yeniden boyutlandırın

matris=matris.reshape(1,5) # 1 satır 5 sütun
print(matris)

# 5 - matris'in boyut sayısını öğrenin

print(matris.shape)



[3 8 2 3 2]
1
[[3 8 2 3 2]]
(1, 5)


# Problem 2

In [33]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

matris2=np.arange(1,10,2)
print(matris2)

# 2 - Oluşturduğunuz matrisi parçalayın

x=np.split(matris2,[1,2])
print(np.split(matris2,[1,2]))

# 3 - Parçalanmış matrisleri birleştirin

print(np.concatenate(x))


[1 3 5 7 9]
[array([1]), array([3]), array([5, 7, 9])]
[1 3 5 7 9]


# Problem 3

In [39]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin

matris3 = np.random.choice(np.arange(5, 101, 2), size=(5, 2))
print(matris3,"\n")

# 2 - matris'in özelliklerini inceleyin

print("Boyut sayısı:",matris3.ndim)
print("Boyut bilgisi:",matris3.shape)
print("Toplam eleman sayısı:",matris3.size)
print("Veri tipi:",matris3.dtype)


[[89 53]
 [21 71]
 [57 31]
 [75 41]
 [89 91]] 

Boyut sayısı: 2
Boyut bilgisi: (5, 2)
Toplam eleman sayısı: 10
Veri tipi: int32
